Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using SistemSales.Data;
using SistemSales.Models;

namespace SistemSales.Controllers
{
    public class BrandController : Controller
    {
        BrandData _BrandData = new BrandData();

        public IActionResult ShowBrands()
        {
            //vist of companys
            var oList = _BrandData.ShowBrands();

            return View(oList);
        }
        public IActionResult CreateBrand()
        {
            //only vist of html formulary
            return View();
        }
        [HttpPost]
        public IActionResult CreateBrand(BrandModel oBrand)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _BrandData.CreateBrand(oBrand);

            if (resp)
                return RedirectToAction("ShowBrands");
            else
                return View();
        }
        public IActionResult EditBrand(int IdBrand)
        {
            var oBrand = _BrandData.GetBrand(IdBrand);
            //only vist of html formulary
            return View(oBrand);
        }
        [HttpPost]
        public IActionResult EditBrand(BrandModel oBrand)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _BrandData.EditBrand(oBrand);

            if (resp)
                return RedirectToAction("ShowBrands");
            else
                return View();
        }
        [HttpPost]
        public IActionResult DeleteBrand(int IdBrand)
        {
            var resp = _BrandData.DeleteBrand(IdBrand);

            if (resp)
                return Ok(); // Si la eliminación es exitosa, devuelve una respuesta 200 OK
            else
                return BadRequest(); // Si hay algún error, devuelve una respuesta 400 Bad Request
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SistemSales.Data;
using SistemSales.Models;

namespace SistemSales.Controllers
{
    public class CategoryController: Controller
    {
        CategoryData _categoryData = new CategoryData();

        public IActionResult ShowCategorys()
        {
            //vist of companys
            var oList = _categoryData.ShowCategorys();

            return View(oList);
        }
        public IActionResult CreateCategory()
        {
            //only vist of html formulary
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryModel oCategory)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _categoryData.CreateCategory(oCategory);

            if (resp)
                return RedirectToAction("ShowCategorys");
            else
                return View();
        }
        public IActionResult EditCategory(int IdCategory)
        {
            var oCategory = _categoryData.GetCategory(IdCategory);
            //only vist of html formulary
            return View(oCategory);
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel oCategory)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _categoryData.EditCategory(oCategory);

            if (resp)
                return RedirectToAction("ShowCategorys");
            else
                return View();
        }
        [HttpPost]
        public IActionResult DeleteCategory(int IdCategory)
        {
            var resp = _categoryData.DeleteCategory(IdCategory);

            if (resp)
                return Ok(); // Si la eliminación es exitosa, devuelve una respuesta 200 OK
            else
                return BadRequest(); // Si hay algún error, devuelve una respuesta 400 Bad Request
        }

    }
}

Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;

using SistemSales.Data;
using SistemSales.Models;

namespace SistemSales.Controllers
{
    public class CompanyController : Controller
    {
        CompanyData _companyData = new CompanyData();

        public IActionResult ShowCompanys()
        {
            //vist of companys
            var oList = _companyData.ShowCompanys();

            return View(oList);
        }
        public IActionResult CreateCompany()
        {
            //only vist of html formulary
            return View();
        }
        [HttpPost]
        public IActionResult CreateCompany(CompanyModel oCompany)
        {
            if(!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _companyData.CreateCompany(oCompany);

            if (resp)
                return RedirectToAction("ShowCompanys");
            else
                return View();
        }
        public IActionResult EditCompany(int IdCompany)
        {
            var oCompany = _companyData.GetCompany(IdCompany);
            //only vist of html formulary
            return View(oCompany);
        }
        [HttpPost]
        public IActionResult EditCompany(CompanyModel oCompany)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _companyData.EditCompany(oCompany);

            if (resp)
                return RedirectToAction("ShowCompanys");
            else
                return View();
        }
        public IActionResult DeleteCompany(int IdCompany)
        {
            var oCompany = _companyData.GetCompany(IdCompany);
            //only vist of html formulary
            return View(oCompany);
        }
        [HttpPost]
        public IActionResult DeleteCompany(CompanyModel oCompany)
        {
            //save object in the database
            var resp = _companyData.DeleteCompany(oCompany.IdCompany);

            if (resp)
                return RedirectToAction("ShowCompanys");
            else
                return View();
        }

    }
}

Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemSales.Data;
using SistemSales.Models;

namespace SistemSales.Controllers
{
    public class SizeController : Controller
    {
        SizeData _SizeData = new SizeData();

        public IActionResult ShowSizes()
        {
            //vist of companys
            var oList = _SizeData.ShowSizes();

            return View(oList);
        }
        public IActionResult CreateSize()
        {
            //only vist of html formulary
            return View();
        }
        [HttpPost]
        public IActionResult CreateSize(SizeModel oSize)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _SizeData.CreateSize(oSize);

            if (resp)
                return RedirectToAction("ShowSizes");
            else
                return View();
        }
        public IActionResult EditSize(int IdSize)
        {
            var oCategory = _SizeData.GetSize(IdSize);
            //only vist of html formulary
            return View(oCategory);
        }
        [HttpPost]
        public IActionResult EditSize(SizeModel oSize)
        {
            if (!ModelState.IsValid)
                return View();
            //save object in the database
            var resp = _SizeData.EditSize(oSize);

            if (resp)
                return RedirectToAction("ShowSizes");
            else
                return View();
        }
        [HttpPost]
        public IActionResult DeleteSize(int IdSize)
        {
            var resp = _SizeData.DeleteSize(IdSize);

            if (resp)
                return Ok(); // Si la eliminación es exitosa, devuelve una respuesta 200 OK
            else
                return BadRequest(); // Si hay algún error, devuelve una respuesta 400 Bad Request
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemSales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemSales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemSales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">

                            

                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="ShowCompanys">Compañias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="ShowSuppliers">Proveedores</a>

                        </li>
                        
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Catalogos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ShowCategorys">Categorias</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="ShowBrands">Marcas</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Size" asp-action="ShowSizes">Tallas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Descount" asp-action="ShowDescounts">Descuentos</a>

                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SistemSales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>